name: deploy
on: [push]

permissions:
  id-token: write   # Needed for OIDC
  contents: read
  
jobs:
  version:
    name: "snow gitactions"
    runs-on: ubuntu-latest
    steps:
      # Checkout step is necessary if you want to use a config file from your repo
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      # Check current folder path
      - name: print current directory
        run: |
          ls $GITHUB_WORKSPACE/
          
      # Snowflake CLI installation
      - uses: snowflakedb/snowflake-cli-action@v2.0
        with:
          cli-version: '3.11.0'   # pick latest stable
          use-oidc: true
          
        # Use the CLI
      - name: Execute Snowflake CLI command
        env: 
          SNOWFLAKE_USER: ${{ secrets.SNOWFLAKE_USER }} 
          SNOWFLAKE_ACCOUNT: ${{ secrets.SNOWFLAKE_ACCOUNT }}
        run: |
          snow stage copy $GITHUB_WORKSPACE @dq_tutorial_db.sch.my_stage --overwrite --recursive -x
          snow sql -q "EXECUTE IMMEDIATE FROM @dq_tutorial_db.sch.my_stage/deploy/warehouse/dev_wh.sql" -x
